### ISSUE TITLE
Fails on AWS RDS due to SET GLOBAL command

### ISSUE THREAD

**Issue by gregharvey** [simplerisk/installer#5]
If you are using AWS RDS, the database as a service from Amazon, as your MySQL back-end then you need to remove lines 512-514 from install/index.php:

```
// Disable ONLY_FULL_GROUP_BY sql_mode
$stmt = $db->prepare("SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));");
$stmt->execute();
```

I'm not entirely sure why they're there, but AWS will not let even the admin user execute this query, but the application installs just fine on RDS once those lines are removed.

Maintainers might consider adding a check for permissions to execute this query before attempting it?

**Comment by jsokol** [comment]
Hey Greg!  Thanks for reporting.  This wasn't an issue with MySQL 5.6, but in MySQL 5.7 they have ONLY_FULL_GROUP_BY mode turned on by default, and this will break SimpleRisk.  That query is designed to disable it so that the queries run properly, but it will only do it while the database is running.  So, if you restart mysql, it comes back.  With a standard mysql install, this is why we have the user change the sql-mode in the MySQL configuration file as well.  

In AWS, you will need to accomplish this same thing, or SimpleRisk will likely not work properly.  To do this, go to Amazon RDS, select "Parameter Group", and either edit your existing parameter group or create a new one to apply to your SimpleRisk RDS.  Search that parameter group for "sql_mode" and ensure that the "Values" set for sql_mode only includes "NO_ENGINE_SUBSTITUTION" or "STRICT_TRANS_TABLES".  These are optional, but anything in addition to them could potentially break SimpleRisk.

In any case, it's interesting that AWS will not allow you to run that query, but the installer wasn't really built for AWS installations.  We can look at fixing that in a future release.  Hopefully the above helps to explain how to make it work, though.

**Comment by gregharvey** [comment]
Hi,

Sorry, I don't ever seem to manage to get GItHub notifications working for me! Only just saw your response. Thanks for that. I'll look into the settings you suggest. Just out of curiosity, how does SimpleRisk break if this mode is not in use? 

Thanks,

Greg

**Comment by jsokol** [comment]
No worries at all.  Long story short, the ONLY_FULL_GROUP_BY mode will throw an error if the "GROUP BY" clause does not include the other columns in the SELECT list and vice versa.  SimpleRisk has a number of queries that were created in this way, specifically around reporting, and those queries will break if you have it turned on.

**Comment by gregharvey** [comment]
Thanks for the clarification! Appreciate it!

**Comment by jsokol** [comment]
Just wanted to follow up with you and let you know that the 20190105-001 installer includes a check for "Super" privileges in mysql.  If that fails, it will skip setting the GLOBAL sql_mode parameter.
